wandb_version: 1

dataset:
  desc: null
  value: dataset/ld50_smiles.json
in_chn:
  desc: null
  value: 9
out_chn:
  desc: null
  value: 128
in_edge:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 32
num_workers:
  desc: null
  value: 0
epoch:
  desc: null
  value: 100
device:
  desc: null
  value: cpu
gpu_type:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738694808
    t:
      1:
      - 1
      - 55
      - 77
      - 105
      2:
      - 1
      - 55
      - 77
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.9.6
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
